- name: Check if screenly-network-manager files exist
  stat:
    path: /usr/sbin/screenly_net_mgr.py
  register: screenly_network_manager

- set_fact: screenly_network_manager_exist="{{screenly_network_manager.stat.exists}}"

- name: Disable network manager
  command: systemctl disable screenly-net-manager.service
  when: screenly_network_manager_exist

- name: Disable network watchdog
  command: systemctl disable screenly-net-watchdog.timer
  when: screenly_network_manager_exist

- name: Remove network manager and watchdog
  file:
    state: absent
    path: "/usr/sbin/{{ item }}"
  with_items:
    - screenly_net_mgr.py
    - screenly_net_watchdog.py

- name: Remove network manager and watchdog unit files
  file:
    state: absent
    path: "/etc/systemd/system/{{ item }}"
  with_items:
    - screenly-net-manager.service
    - screenly-net-watchdog.service

- name: Remove network watchdog timer file
  file:
    state: absent
    path: /etc/systemd/system/screenly-net-watchdog.timer

# Use resin-wifi-connect if Stretch
- debug:
    msg: "Manage network: {{ manage_network }}"

- name: Add pi user to Identity
  replace:
    regexp: '^Identity=.*'
    replace: 'Identity=unix-group:netdev;unix-group:sudo:pi'
    dest: /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla
  when:
    - manage_network|bool == true

- name: Set ResultAny to yes
  replace:
    regexp: '^ResultAny=.*'
    replace: 'ResultAny=yes'
    dest: /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla
  when:
    - manage_network|bool == true

- name: Copy org.freedesktop.NetworkManager.pkla to 50-local.d
  command: cp -f /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla /etc/polkit-1/localauthority/50-local.d
  when:
    - manage_network|bool == true

- name: Disable dhcpcd
  command: systemctl disable dhcpcd
  when:
    - ansible_distribution_major_version|int >= 9
    - manage_network|bool == true

- name: Activate NetworkManager
  command: systemctl enable NetworkManager
  when:
    - ansible_distribution_major_version|int >= 9
    - manage_network|bool == true
