- name: Check if screenly-network-manager files exist
  stat:
    path: /usr/sbin/screenly_net_mgr.py
  register: screenly_network_manager

- set_fact: screenly_network_manager_exist="{{screenly_network_manager.stat.exists}}"

- name: Disable network manager
  command: systemctl disable screenly-net-manager.service
  when: screenly_network_manager_exist

- name: Disable network watchdog
  command: systemctl disable screenly-net-watchdog.timer
  when: screenly_network_manager_exist

- name: Remove network manger and watchdog
  file:
    state: absent
    path: "/usr/sbin/{{ item }}"
  with_items:
    - screenly_net_mgr.py
    - screenly_net_watchdog.py

- name: Remove network manager and watchdog unit files
  file:
    state: absent
    path: "/etc/systemd/system/{{ item }}"
  with_items:
    - screenly-net-manager.service
    - screenly-net-watchdog.service

- name: Remove network watchdog timer file
  file:
    state: absent
    path: /etc/systemd/system/screenly-net-watchdog.timer

- name: Copy wifi conf 
  copy:
    src: wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0755

